spring.jpa.open-in-view: false

spring:
  application:
    name: linkservice
  datasource:
    url: ${DB_URL:jdbc:oracle:thin:@db-oracle:1521/XEPDB1}
    username: ${DB_USER:pdbadmin}
    password: ${DB_PWD:123}

flyway:
  url: ${DB_URL:jdbc:oracle:thin:@db-oracle:1521/XEPDB1}
  schemas: ${DB_USER:pdbadmin}
  user: ${DB_USER:pdbadmin}
  password: ${DB_PWD:123}

server:
  port: ${SERVER_PORT:8080}



linkservice.max-link-length: 13