spring:
  application:
    name: linkservice
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: pdbadmin
    password: 123

flyway:
  url: jdbc:oracle:thin:@localhost:1521/XEPDB1
  schemas: pdbadmin
  user: pdbadmin
  password: 123