version: "3.9"

services:

  redirect-service:
    build: ../redirectservice
    ports:
      - 8084:8080
    environment:
      - SERVER_PORT=8080
      - LINK_SERVICE_URL=http://link-service:8080
    depends_on:
      - link-service

  link-service:
    build: ../linkservice/service
    ports:
      - 8083:8080
    environment:
      - DB_URL=jdbc:oracle:thin:@db-oracle:1521/XEPDB1
      - DB_USER=pdbadmin
      - DB_PWD=123
      - SERVER_PORT=8080
    depends_on:
       db-oracle:
         condition: service_healthy

  db-oracle:
    environment:
      - ORACLE_PWD=123
      - ORACLE_CHARACTERSET=UTF8
    ports:
      - 1521:1521
    volumes:
      - ./oracle_startup_scripts:/opt/oracle/scripts/startup  # makes oracle execute those scripts at startup
    image: container-registry.oracle.com/database/express


# docker run --name oracle-db -p 1521:1521 -p 5500:5500 -e ORACLE_PWD=123 -e ORACLE_CHARACTERSET=UTF8 -v /home/konstantin/IdeaProjects/rtk-test-task/linkservice/sql_scripts:/opt/oracle/scripts/startup container-registry.oracle.com/database/express
# docker compose build --no-cache
# docker compose up