server:
  port: ${SERVER_PORT:8081}

spring:
  cloud:
    openfeign:
      client:
        config:
          link-service:
            url: ${LINK_SERVICE_URL:"http://link-service:8080"}


feign:
  client:
    config:
      default:
        connectTimeout: ${CONNECT_TIMEOUT:5000}
        readTimeout: ${READ_TIMEOUT:5000}
        loggerLevel: basic
