server:
  port: 8081

spring:
  cloud:
    openfeign:
      client:
        config:
          link-service:
            url: "http://localhost:8080"


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
